version: '3.4'

services:
  mssql:
    image: mcr.microsoft.com/mssql/server:2019-latest
    ports:
      - 1450:1433
    container_name: sqlserver-container
    volumes:
      - c:\dados\volumes\mssql:/var/opt/mssql/data
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=Numsey#2022
    restart: always

  goiabaAPI:
    image: ${DOCKER_REGISTRY-}goiabaapi
    build:
      context: .
      dockerfile: .
    ports:
      - 8081:80
    container_name: goiabaApi-container
    restart: always
    depends_on:
      - mssql